name: ErosLab Wallpapers Bot

on:
  schedule:
    - cron: '30 */2 * * *'
  workflow_dispatch:

jobs:
  post_wallpapers:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
          
      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt


      - name: Run Wallpapers Bot
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
          TELEGRAM_BOT_TOKEN_WALLPAPERS: ${{ secrets.TELEGRAM_BOT_TOKEN_WALLPAPERS }}
          TELEGRAM_CHANNEL_ID_WALLPAPERS: ${{ secrets.TELEGRAM_CHANNEL_ID_WALLPAPERS }}
          ADMIN_USER_ID: ${{ secrets.ADMIN_USER_ID }}
          CIVITAI_API_KEY: ${{ secrets.CIVITAI_API_KEY }}
          STATS_TZ: "Europe/Moscow"
        run: python wallpapers_bot.py
        
